### ISSUE TITLE
User registration when registering for a course does not send mail with credentials to user

### ISSUE THREAD

**Issue by vicskf** [educatorplugin/ib-educator#1]
I haven´t looked deep into it so I don't really know what's causing this. But I think a simple solution would be to not show the payment form until logged in. So to do this we could split the payment process in shortcode-payment.php into on more step, maybe?
What do you think @educatorplugin ?

**Comment by educatorplugin** [comment]
Hi. Thanks for this report. Will look into this issue.

**Comment by educatorplugin** [comment]
Hi. The issue was in the Educator plugin. It was fixed in the latest version (currently, 1.7.1). Please update this plugin to 1.7.1 and please read the change log before updating - https://wordpress.org/plugins/ibeducator/changelog/

**Comment by vicskf** [comment]
Thanks for update! Works perfect now.
